<?php

// Define constants for module variables
//
// MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_ENABLED
// MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_LISTS
// MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_CONTENT_TYPES

$module_variables = variable_get('mailjet_simple_node_campaigns_settings', array());

foreach($module_variables as $key => $value) {
  define('MAILJET_SIMPLE_NODE_CAMPAIGNS_' . strtoupper($key), $value);
}

/**
 * Implements hook_menu().
 */
function mailjet_simple_node_campaigns_menu() {
  $items = [];

  $items['admin/config/services/mailjet-simple/node-campaigns'] = array(
    'title' => 'Node Campaign Settings',
    'description' => t('Configure Mailjet Simple Node Campaigns Module Settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mailjet_simple_node_campaigns_admin_settings_form'),
    'access arguments' => array('administer mailjet simple'),
    'file' => 'includes/mailjet_simple_node_campaigns.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Defines default settings array.
 */
function mailjet_simple_node_campaigns_settings_defaults() {
  return [
    'node_campaign_lists' => [],
  ];
}


/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function mailjet_simple_node_campaigns_form_node_form_alter(&$form, $form_state) {
  // Alter node form configured to be used as a node campaign.
  if (($form['type']['#value'] == MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_CONTENT_TYPES) && MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_ENABLED !== 0) {

    $form['mailjet_simple_node_campaigns_settings'] = array(
      '#type' => 'fieldset',
      '#access' => TRUE,
      '#title' => t('Mailjet: Node Campaign Settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
      '#attributes' => array(
        'class' => array('mailjet-simple-node-campaigns-settings'),
      ),
      '#attached' => array(
        'js' => array(drupal_get_path('module', 'mailjet_simple_node_campaigns') . '/mailjet-simple-node-campaigns-node-form.js')
      ),
      '#weight' => 89,
    );

    // Send campaign on save default value based on node create or node edit.
    $default_value = 0;
    if (empty($form['nid']['#value'])) {
      $default_value = 1;
    }

    $form['mailjet_simple_node_campaigns_settings']['create_and_send'] = array(
      '#type' => 'checkbox',
      '#title' => t('Create and Send Campaign on Save?'),
      '#default_value' => $default_value,
    );

    $form['#submit'][] = 'mailjet_simple_node_campaigns_form_node_form_submit';
  }
}

/**
 * Form submit handler.
 */
function mailjet_simple_node_campaigns_form_node_form_submit($form, &$form_state) {
  // Prepare Mailjet campaign.
  mailjet_simple_prepare_campaign(MAILJET_SIMPLE_NODE_CAMPAIGNS_NODE_CAMPAIGN_LISTS, $title = $form_state['values']['title'], $message = $form_state['values']['body'][LANGUAGE_NONE][0]['value']);
}
